### ISSUE TITLE
Simulador de un Jefe Técnico de MotoGP

### ISSUE THREAD

**Issue by arnel-sanchez** [matcom/ia-sim-cmp-21#1]
## Datos del proyecto

> Complete la siguiente información

**Nombre:**: Simulador de un Jefe Técnico de MotoGP
**Repositorio**: https://github.com/arnel-sanchez/IA-Sim-Com
**Reporte**: https://github.com/arnel-sanchez/IA-Sim-Com/blob/master/Informe/Informe.pdf

## Breve resumen

> Este resumen (o uno ligeramente más amplio) debe aparecer también en el reporte linkeado arriba.

Existirán varios pilotos con sus respectivas motos, las cuáles difieren entre sí en cuanto a sus prestaciones. Cada piloto posee su propio método de manejo, siendo algunos más cuidadosos y otros más agresivos. La pista se encuentra influenciada por el accionar del clima, puesto que no es lo mismo el manejo durante un día soleado que bajo la lluvia. Por tanto, el resultado de un piloto se verá condicionado por su moto, su modo de conducción y el clima.
	Sin embargo, durante la carrera las condiciones pueden variar y el Jefe Técnico será el encargado de señalar los ajustes necesarios que el piloto deberá hacer para mejorar su rendimiento. Dicho intercambio de información se hará al finalizar cada vuelta utilizando un lenguaje imperativo, mediante el uso de palabras claves para que el piloto no necesite analizar situaciones complejas y pueda concentrarse en pilotar de la forma mas eficiente posible.
	De esta manera, la simulación de la carrera será dinámica, puesto que entre las vueltas podrán existir variaciones provocadas por los ajustes propuestos por el Jefe Técnico, el cuál podrá ser una persona o una IA.

## Miembros del equipo

- Arnel Sánchez Rodríguez (@arnel-sanchez)
- Samuel Efraín Pupo Wong (@SamuelPupo)
- Darián Ramón Mederos  (@darianramon)

## Aprobación

> Estos elementos serán chequeados por los profesores de la asignatura para aprobar el proyecto.

- [x] El repositorio indicado existe
- [x] El documento de reporte existe, y tiene la estructura inicial (nombre del proyecto, autores, breve descripción)
- [x] Los miembros del equipo tienen usuarios en Github debidamente identificados (avatar, nombre completo, y página de perfil)
- [x] El resumen describe una idea factible y de complejidad adecuada

En caso de que algunas de las condiciones anteriores no se cumplan, en este issue les dejaremos todos los comentarios y discusiones necesarias para lograr la aprobación del proyecto.

Este issue será cerrado una vez se considere definitivamente aprobado o rechazado el proyecto, y se le pondrá la etiqueta correspondiente.

**Comment by apiad** [comment]
El perfile @darianramon está un poco crudo, al menos ponle un avatar (no tiene porque ser tu foto real, pero algo) y el nombre completo.

**Comment by apiad** [comment]
> No entendemos a lo que se refiere con "Así mismo me gustaría que la inteligencia de los pilotos se pudiera programar de antemano"

Básicamente que lo que cada piloto va a hacer en cada momento no esté predefinido por ustedes del todo, sino que el usuario pueda implementar en el DSL estrategias que ellos seguirán. Puede ser algo como durante la competencia habrá eventos, no sé, se te mete un carro delante, viene una curva, un bache, y el piloto puede escoger diferentes opciones, y algunos pilotos serán más arriesgados que otros, entonces yo quiero poder programar cómo reacciona ante cada una de esas condiciones.

Igual con el tal jefe técnico, no quisiera como un juego en tiempo real donde el usuario tiene que escribir un comando, sino que el usuario programa de antemano la estrategia del jefe técnico, si pasa esto entonces haz esto, si pasa esto otro, de forma que lo que puedes simular y evaluar son diferentes estrategias.

**Comment by SamuelPupo** [comment]
> 
> 
> > No entendemos a lo que se refiere con "Así mismo me gustaría que la inteligencia de los pilotos se pudiera programar de antemano"
> 
> Básicamente que lo que cada piloto va a hacer en cada momento no esté predefinido por ustedes del todo, sino que el usuario pueda implementar en el DSL estrategias que ellos seguirán. Puede ser algo como durante la competencia habrá eventos, no sé, se te mete un carro delante, viene una curva, un bache, y el piloto puede escoger diferentes opciones, y algunos pilotos serán más arriesgados que otros, entonces yo quiero poder programar cómo reacciona ante cada una de esas condiciones.
> 
> Igual con el tal jefe técnico, no quisiera como un juego en tiempo real donde el usuario tiene que escribir un comando, sino que el usuario programa de antemano la estrategia del jefe técnico, si pasa esto entonces haz esto, si pasa esto otro, de forma que lo que puedes simular y evaluar son diferentes estrategias.

Se supone que habra pilotos y jefes tecnicos predefinidos, por lo que la opcion de jugar en tiempo real no es independiente de que los pilotos y los jefes tomen sus propias decisiones.

Cuando tu eres el jefe tecnico que habla con el piloto, le das sugerencias de como mejorar su carrera, pero el piloto tiene caracteristicas propias que influiran en esa decision. Por ejemplo: si le dices que aumente la velocidad porque es muy lento, esta lloviendo y es cuidadoso, no habra mucho efecto en esa orden (no se va a poner en peligro); por el contrario: si es agresivo y le dices que aumente la velocidad, aumenta la probabilidad de caerse.

Si el jefe tecnico se preocupa mas por ganar que por el bienestar del piloto, puede darle ordenes que sean arriesgadas. Por el contrario, si quiere que el piloto solo termine la carrera, puede pedirle que tenga mas cuidado en las curvas.

Se puede simular todo tipo de cosas (configurables, por supuesto) pero que tendran tambien modelos predefinidos.

Por eso es que dar ordenes en tiempo real (que sera opcional) no es contradictorio con el hecho de que se autoconfiguren cosas de antemano.

**Comment by SamuelPupo** [comment]
> 
> 
> > No entendemos a lo que se refiere con "Así mismo me gustaría que la inteligencia de los pilotos se pudiera programar de antemano"
> 
> Básicamente que lo que cada piloto va a hacer en cada momento no esté predefinido por ustedes del todo, sino que el usuario pueda implementar en el DSL estrategias que ellos seguirán. Puede ser algo como durante la competencia habrá eventos, no sé, se te mete un carro delante, viene una curva, un bache, y el piloto puede escoger diferentes opciones, y algunos pilotos serán más arriesgados que otros, entonces yo quiero poder programar cómo reacciona ante cada una de esas condiciones.
> 
> Igual con el tal jefe técnico, no quisiera como un juego en tiempo real donde el usuario tiene que escribir un comando, sino que el usuario programa de antemano la estrategia del jefe técnico, si pasa esto entonces haz esto, si pasa esto otro, de forma que lo que puedes simular y evaluar son diferentes estrategias.

Realmente todo tipo de cosas simulables pueden ser configurables antes de iniciar y durante la carrera.

Hacerlo con el DSL seria lo mas logico, para lo cual habria que definir cada uno de estos comandos con los que se interactuara con el programa. Pero como nunca hemos trabajado con uno es donde mas necesitaremos su vision y su ayuda con respecto a que ideas son mas claras y mas factibles (para evitar entrar en callejones sin salida).

**Comment by arnel-sanchez** [comment]
@apiad cuando pueda nos echa un vistazo al proyecto
